### ISSUE TITLE
Broadcast to all but sender

### ISSUE THREAD

**Issue by hackmushroom** [oncesk/yii-node-socket#73]
Great module!

How can I emit a message to all users (not in a room or channel) EXCLUDING the sender?
I.e. socket.broadcast.emit() ??

I've got everything working, just can't stop the sender from receiving their own message.

**Comment by oncesk** [comment]
Hi, yes, did you tried socket.broadcast.emit ?
22 марта 2016 г. 19:22 пользователь "hackmushroom" <notifications@github.com>
написал:

**Comment by hackmushroom** [comment]
Yeah it was the first thing I tried but I get "socket.broadcast is
undefined"

I'll put some code up later

**Comment by hackmushroom** [comment]
Okay, so here's what I tried. For now this is javascript (YiiNodeSocket) based (I also have no idea how you would broadcast from php using  frame->send() either)

```
 <script type="text/javascript">
        $(function () {

            var socket = new YiiNodeSocket();

            socket.on('message', function (message) {
                console.log(message);
            });

            socket.onConnect(function () {
                $('#test').on('click', function(){
                    socket.emit('message', 'Hello to all'); // <-- Works fine
                    socket.broadcast.emit('message', 'Hello to all but me'); // <-- TypeError: socket.broadcast.emit is not a function
                });
            });
        });
    </script>
```

All js scripts appear to be loaded okay (socket.io.js & client/client.js). My socket.io version is showing as 0.9.4.. is this right?

**Comment by oncesk** [comment]
Hi, seems like now i am understand what are you need,

When you create socket aka

socket = new YiiNodeSocket

socket has no broadcast method because it is not a socket.io instance,
elsewhere client socket.io has no method broadcast, you just can call some
method on the server via emit from client and server can call emit or
broadcast.emit

Maybe ask your questions to me and we can think how to do what are you need
23 марта 2016 г. 17:32 пользователь "hackmushroom" <notifications@github.com>
написал:

**Comment by hackmushroom** [comment]
I've managed to work out how to achieve this, I'll create a pull request later after some testing

**Comment by oncesk** [comment]
thank you, i will close issue
